### ISSUE TITLE
Adding "Center Center" position option

### ISSUE THREAD

**Issue by amansaini** [hakanersu/AmaranJS#12]
Is there any way the notification can be positioned at center of screen?

**Comment by hakanersu** [comment]
Hi @amansaini actually we have 'center center' position but there is a few issues.As for now better to use  single amaranjs notification and set your amaranjs wrapper with to notification width.

For example : http://jsfiddle.net/qtmebjp0/1/

I will try to fix issues about center positioning.

**Comment by amansaini** [comment]
Thanks !!!

**Comment by hakanersu** [comment]
I suggest use like this (at least for now) : http://jsfiddle.net/qtmebjp0/3/

Have a nice day.

**Comment by amansaini** [comment]
thankyou ...that looks perfect to me.
Thanks for responding so quickly and all your help.

Good day.
