### ISSUE TITLE
CDN 

### ISSUE THREAD

**Issue by KrishnaPG** [hakanersu/AmaranJS#15]
Is this package available on any CDN?

I am planning to use this (the theme capability is good feature) - but downloading and maintaining local copies would be problematic. Hence hesitating.

Wondering if this could be made available on any CDN (e.g., https://github.com/cdnjs/cdnjs ) so that more people can get access to it and easy to maintain.

**Comment by hakanersu** [comment]
Hi yes cdn already available, just check http://www.jsdelivr.com/#!jquery.amaran

**Comment by KrishnaPG** [comment]
Ok, that's cool.

Since on the documentation and the `ReadMe.md` it has this kind of code `<script src="/js/jquery.amaran.js"></script>` thought it did not have CDN.

So, instead I just have to do `src="//cdn.jsdelivr.net/jquery.amaran/0.5.3/jquery.amaran.min.js"` Right?

Cool. Will give it a try and also spread the word about it.

**Comment by KrishnaPG** [comment]
Also, for those who are looking for `animate.css` on CDN, found it here on cdnjs:
`//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.3/animate.min.css`
