### ISSUE TITLE
Feature for local vs global positioning?

### ISSUE THREAD

**Issue by KrishnaPG** [hakanersu/AmaranJS#17]
Thank you for sharing the good work.

Just wondering if it would be possible to include element specific notifications (like this one at http://notifyjs.com/ does).

For example, when specified something like `$(".textbox").amaran()` the notification would be displayed relative to that textbox, which would be great way to show errors and all for inputs.

**Comment by hakanersu** [comment]
I will look at it but it is very tricky with current plugin structure.
