### ISSUE TITLE
How to customize the close x button in custom theme

### ISSUE THREAD

**Issue by KrishnaPG** [hakanersu/AmaranJS#18]
My custom theme has slightly light (white) background and as such the close button (the small x button on the top right corner) is not visible.

How to customize its appearance? Would like to change its color to something dark.

**Comment by hakanersu** [comment]
You can change via css;

```
.amaran-close:before {
	color:#000;
}
```

**Comment by KrishnaPG** [comment]
Thanks for the fast response. But for some unknown reason, it is getting overwritten as shown in the screen capture below: 
![image](https://cloud.githubusercontent.com/assets/4610831/6661975/80d9ee88-cbdb-11e4-92f0-c8b9ceacaf34.png)

I was able to customize `mytheme` etc. fine - but for this one  my customization are getting overwritten.

**Comment by hakanersu** [comment]
Can you provide any example link? or try to add !important
```
.amaran-close:before {
    color:#000 !important;
}
```

**Comment by KrishnaPG** [comment]
Thanks - looks like this `!important` is retaining my selected color and not overwriting. Just wondering why ":before" was used though. Usually I think thats more like a JS trick to insert elements and not a CSS trick, right?

**Comment by hakanersu** [comment]
Actually i usally use js to do it but for this situation :before is very useful.You can use custom font type icons  like fontawesome's close button,

```
.amaran-close {
   font:normal normal normal 14px/1 FontAwesome
}
.amaran-close:before {
  content: "\f00d";
}
```

**Comment by KrishnaPG** [comment]
Ok - that make sense. Thanks.
