### ISSUE TITLE
How to prevent message from disappearing while mouse is on it?

### ISSUE THREAD

**Issue by KrishnaPG** [hakanersu/AmaranJS#19]
Messages are automatically disappearing after sometime, which is great.

But, I would like to keep the message there if user hovers his mouse on it (perhaps, he is examining the message content).

The use case is like this:
    1. By default, messages should disappear after some time as usual, if user does nothing about them 
    2. However, if user hovers the mouse on it (then he may want to select and copy the content of the message with mouse), then the message should become sticky that gets close only upon click of the x button. 

How to achieve this. One way is:

  this library can have a new option something like "no autoclose on hover" that when set to true, changes it behavior to be "sticky=true, closeOnClick=false, closeButton=true" automatically whenever mouse hovers on any message.

The otherway is, to reset and renew the timer to be some configurable value user passes on, like this one does here: http://codeseven.github.io/toastr/demo.html 
Select the "progressbar" option and hover the mouse on the message - it renews the timer.

**Comment by hakanersu** [comment]
Very good idea i will definitely try to implement this feature.

**Comment by KrishnaPG** [comment]
For now, I am using long timeout delay with below configuration, so that customer can select the error message text using mouse and copy it. But occasionally, while selecting and copying it times out and message disappears, leaving the user baffled. Perhaps some kind of progress bar (like the one here http://codeseven.github.io/toastr/demo.html) or a `make it sticky` button next to close button should be good.
````
        'delay': 10000,
        'sticky'        :false, /* make it go away after some time */
        'closeOnClick'  :false, /* let user be able to select text with mouse */
        'closeButton'   :true,  /* Explicit close button to manually close */
````
Sticky is set to false, so that those messages that user doesn't want to attend to will go away auto-magically. 
closeOnClick is false, so user can select the text with mouse

**Comment by hakanersu** [comment]
@KrishnaPG I updated code and added new option **resetTimeout** this option allow to reset timeout when hover.I will update this option later and i will add events to resetTimeout.(onclick,mouseenter etc.)
