### ISSUE TITLE
Bug clearAll : true

### ISSUE THREAD

**Issue by usb248** [hakanersu/AmaranJS#26]
I've discover your plugin, and directly, first bug.

when we call in first time $.amaran() for one notification with option 'overlay' :true, and then, in second time we call $.amaran() with 'clearAll' :true, all previous notif removed but not the overlay...

```javascript
     $.amaran({
			'theme'     :'colorful',
			'overlay' :true,
			'sticky':true,
			'content'   :{
			   bgcolor:'#199be9',
			   color:'#fff',
			   message: 'Loading ...'
			},
			'position'  :'bottom right',
			'outEffect' :'slideRight'
		});
		
		setTimeout(function(){
			$.amaran({
				'message'       :'My first example!',
				'clearAll'      :true
			});		
		},3000);
```

**Comment by hakanersu** [comment]
Thank you for bug report. Actually i did implement overlay by request and it seems i didnt test very well. I will fix issue as soon as i can but you can add $('.amaran-overlay').remove() to your setTimeout function for quick dirty fix.

**Comment by usb248** [comment]
Yes, i know but it's not very "pretty". Moreover, i noticed, that the overlay appear with any transition but disappear with transition, why ?

**Comment by hakanersu** [comment]
I thought it was a bit ugly that removing overlay without transition. So like i said i did implement this feature by a user request and didn't get any feedback. If you want i can add transition option for overlay with color option.

**Comment by usb248** [comment]
why not, but color option is not necessary, we can modifing CSS.

**Comment by WaynePhipps** [comment]
I know this appears an old thread but I'm interested in the same point, that the overlay appears without a transition and is then slow to `fadeOut`.

This adds a delay when the notification is closed before the user can then interact with the UI.

I actually was looking for some way to decrease the duration of the `fadeOut` on the overlay but cant see where this is controlled. I'm guessing perhaps the answer lies within `animate.css` but I haven't yet tracked it down.

Great work by the way, I'm using this now instead of Toastr

**Comment by hakanersu** [comment]
Hi @WaynePhipps 

I will fix this issue soon ( 3-4 days later, im at holiday :) ). But before that let me explain how it works.

Overlay remove function  runs after each element removed from dom ([removeIt()](https://github.com/hakanersu/AmaranJS/blob/master/src/coffee/jquery.amaran.coffee#L228)). So when last notification transition ends this functions runs, after that it seems i added 400ms fadeOut. So for fix ill move overlay remove function to notification close function and except fadeOut ill hide overlay.

**Comment by WaynePhipps** [comment]
Wow, @hakanersu. Many thanks, that does help and much appreciated.

There's no rush, enjoy your holiday but thanks for your explanation and response.

**Comment by hakanersu** [comment]
New option added **overlayColor**. Better to use rgba color like ```rgba(16, 0, 255, 0.49)```
