### ISSUE TITLE
What is the new page for Demo and Documentation?

### ISSUE THREAD

**Issue by ankushdharkar** [hakanersu/AmaranJS#27]
I tried to access the demo and documentation at http://hakanersu.github.io/AmaranJS/, but was redirected to http://ersu.me/cgi-sys/suspendedpage.cgi which says: 

```
This Account has been suspended.
Contact your hosting provider for more information.
```

Could you please provide us with the link to the new page where the Demo and Documentation has migrated to in the `README.md`. I was unable to find it online. Seems like a recent issue.

**Comment by hakanersu** [comment]
It must be working now. Thank you for reporting.

**Comment by ankushdharkar** [comment]
It's working again. Thank you.
