### ISSUE TITLE
i call a function onclick then show amaran notification then this errors occurs [SOLVED]

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [hakanersu/AmaranJS#34]
> jquery.amaran.min.js:1` Uncaught TypeError: Cannot read property 'top' of undefined

    at o.getInfo (jquery.amaran.min.js:1)
    at o.getPosition (jquery.amaran.min.js:1)
    at o.slide (jquery.amaran.min.js:1)
    at o.animation (jquery.amaran.min.js:1)
    at o.close (jquery.amaran.min.js:1)
    at new o (jquery.amaran.min.js:1)
    at Function.t.amaran (jquery.amaran.min.js:1)
    at showToast (tikman.js:56)
    at Object.success (<anonymous>:34:1)
    at u (jquery.min.js:2)
getInfo @ jquery.amaran.min.js:1
getPosition @ jquery.amaran.min.js:1
slide @ jquery.amaran.min.js:1
animation @ jquery.amaran.min.js:1
close @ jquery.amaran.min.js:1
o @ jquery.amaran.min.js:1
t.amaran @ jquery.amaran.min.js:1
showToast @ tikman.js:56
success @ VM2364:34
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
tryToConnect @ VM2364:28
onclick @ (index):1
jquery.min.js:2 

> 

check image:
https://ibb.co/xGL1dpZ

**Comment by hakanersu** [comment]
Can you share your code?

**Comment by muhammadarsalansiddiqui** [comment]
> Can you share your code?

which code ?

**Comment by muhammadarsalansiddiqui** [comment]
function showToast($toastMessage){
$.amaran({

'content':{ title: siteName, message: $toastMessage },
'position':'top right',
'theme':'tumblr',
'overlay':false,
'sticky':true,
'inEffect':'slideTop',
'outEffect':'slideBottom',
'closeButton':true,
'closeOnClick':false

});
}

- - - - - - - - - -

function tryToConnect(nasId){
$.ajax({
url: "pages/background-process-try-to-connect.php",
type: 'POST',
data: 'nasId='+nasId,
cache: false,
success: function(ss){
showToast(ss);
}
});
}

**Comment by hakanersu** [comment]
I updated plugin, please download update your jquery.amaran.min.js file.

**Comment by marsalans** [comment]
Fixed, Thank you @hakanersu
